#!/usr/bin/env python3
#
# Unpacks a JSON file exported from BigQuery httparchive table.

import json
import os
import sys

def unjson(path):
    with open(path, mode='rt', encoding='utf-8') as f:
        data = json.load(f)
    page = data['page']
    url = data['url']
    body = data['body']

    outpath = os.path.splitext(path)[0] + '.txt'
    with open(outpath, mode='wt', encoding='utf-8') as f:
            f.write('page: %s\n' % page)
            f.write('url: %s\n' % url)
            f.write('\n')
            f.write(body)

if __name__ == '__main__':
    for path in sys.argv[1:]:
        try:
            unjson(path)
        except:
            print('Failed to extract ' + path)
